# Generated by Django 6.0.6 on 2026-07-08 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Descriptive name for the prompt', max_length=255)),
                ('content', models.TextField(help_text='The system prompt text sent to the LLM')),
                ('is_active', models.BooleanField(default=False, help_text='Only one prompt per role can be active at a time')),
                ('role', models.CharField(choices=[('actor', 'Actor'), ('summary', 'Summary'), ('graph', 'Graph')], default='actor', help_text='Role this prompt serves: actor (chat bot) | summary (website summary)', max_length=20)),
                ('lang', models.CharField(choices=[('eng', 'ENG'), ('ger', 'GER')], default='en', help_text='Language of the prompt', max_length=5)),
            ],
            options={
                'verbose_name': 'Chat System Prompt',
                'verbose_name_plural': 'Chat System Prompts',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Title of the conversation', max_length=255)),
                ('messages', models.JSONField(default=list, help_text='Chat messages stored as JSON array')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='web.website')),
            ],
            options={
                'verbose_name': 'Chat History',
                'verbose_name_plural': 'Chat Histories',
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'website'], name='chat_chathi_user_id_f4444a_idx')],
            },
        ),
    ]
