# Generated by Django 6.0.6 on 2026-07-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsystemprompt',
            name='lang',
            field=models.CharField(choices=[('eng', 'ENG'), ('ger', 'GER')], default='eng', help_text='Language of the prompt', max_length=5),
        ),
        migrations.AlterField(
            model_name='chatsystemprompt',
            name='role',
            field=models.CharField(choices=[('chat', 'Chat'), ('summary', 'Summary'), ('graph', 'Graph')], default='actor', help_text='Role this prompt serves: actor (chat bot) | summary (website summary)', max_length=20),
        ),
    ]
