# Generated by Django 6.0.6 on 2026-09-10 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatsystemprompt_lang_and_more'),
        ('web', '0003_website_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chathistory',
            name='chat_chathi_user_id_f4444a_idx',
        ),
        migrations.AddConstraint(
            model_name='chathistory',
            constraint=models.UniqueConstraint(fields=('user', 'website'), name='unique_chat_history_per_user_website'),
        ),
    ]
