# Generated by Django 6.0.6 on 2026-07-08 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Sentence',
                'verbose_name_plural': 'Sentences',
                'ordering': ['website', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('PERSON', 'Person'), ('ORG', 'Organization'), ('GPE', 'Country/City/State'), ('LOC', 'Location'), ('NORP', 'Nationality/Religious/Political group')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to=settings.AUTH_USER_MODEL)),
                ('sentences', models.ManyToManyField(related_name='entities', to='web.sentence')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'ordering': ['user', 'entity_name'],
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relation Type',
                'verbose_name_plural': 'Relation Types',
                'ordering': ['user', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_first', to='web.entity')),
                ('entity2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_second', to='web.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to=settings.AUTH_USER_MODEL)),
                ('relation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.relationtype')),
                ('sentences', models.ManyToManyField(related_name='relations', to='web.sentence')),
            ],
            options={
                'verbose_name': 'Relation',
                'verbose_name_plural': 'Relations',
                'ordering': ['user', 'entity1', 'entity2'],
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.TextField(help_text='URL of the website')),
                ('content', models.TextField(help_text='Scraped and normalized content of the website')),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 of content. Used to detect page changes and invalidate the cached summary.', max_length=64)),
                ('summary', models.TextField(blank=True, help_text='Rough LLM-generated sumary, used as chat context. Cleared when content_hash changes.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='sentence',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='web.website'),
        ),
        migrations.CreateModel(
            name='WebsiteEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.entity')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.website')),
            ],
            options={
                'verbose_name': 'Website Entity Occurrence',
                'verbose_name_plural': 'Website Entity Occurrences',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='websites',
            field=models.ManyToManyField(related_name='entities', through='web.WebsiteEntity', to='web.website'),
        ),
        migrations.AddConstraint(
            model_name='relationtype',
            constraint=models.UniqueConstraint(fields=('user', 'label'), name='unique_relationtype_per_user'),
        ),
        migrations.AddConstraint(
            model_name='relation',
            constraint=models.UniqueConstraint(fields=('user', 'entity1', 'entity2', 'relation_type'), name='unique_relation_per_user'),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('user', 'url'), name='unique_website_per_user'),
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['website'], name='web_sentenc_website_504bb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='websiteentity',
            constraint=models.UniqueConstraint(fields=('website', 'entity'), name='unique_website_entity'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('user', 'entity_name', 'entity_type'), name='unique_entity_per_user'),
        ),
    ]
