# Generated by Django 6.0.6 on 2026-08-17 13:54

from django.db import migrations, models


def backfill_relation_websites(apps, schema_editor):
    Relation = apps.get_model('web', 'Relation')
    through = Relation.websites.through

    rows = []
    for relation in Relation.objects.prefetch_related('sentences'):
        for website_id in {s.website_id for s in relation.sentences.all()}:
            rows.append(through(relation_id=relation.id, website_id=website_id))

    through.objects.bulk_create(rows, ignore_conflicts=True)


def noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='origin',
            field=models.CharField(choices=[('PIPELINE', 'Extracted'), ('MANUAL', 'User added')], default='PIPELINE', max_length=10),
        ),
        migrations.AddField(
            model_name='relation',
            name='websites',
            field=models.ManyToManyField(related_name='relations', to='web.website'),
        ),
        migrations.AddField(
            model_name='websiteentity',
            name='origin',
            field=models.CharField(choices=[('PIPELINE', 'Extracted'), ('MANUAL', 'User added')], default='PIPELINE', max_length=10),
        ),
        migrations.RunPython(backfill_relation_websites, noop),
    ]


