# Generated by Django 6.0.6 on 2026-08-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_relation_origin_relation_websites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='title',
            field=models.TextField(blank=True, default='', help_text='Page title, used to label this source in the graph UI'),
        ),
    ]
