# Generated by Django 6.0.6 on 2026-09-10 12:48

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_website_title'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.UniqueConstraint(models.F('website'), django.db.models.functions.text.MD5('text'), name='unique_sentence_per_website'),
        ),
    ]
