# Generated by Django 6.0.6 on 2026-09-11 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_sentence_unique_sentence_per_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='master',
            field=models.ForeignKey(blank=True, help_text='Set when this entity was merged into another.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='web.entity'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.CheckConstraint(condition=models.Q(('master', models.F('id')), _negated=True), name='entity_master_not_self'),
        ),
    ]
