# Generated by Django 6.0.6 on 2026-09-11 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_entity_master_entity_entity_master_not_self'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relation',
            constraint=models.UniqueConstraint(condition=models.Q(('relation_type__isnull', True)), fields=('user', 'entity1', 'entity2'), name='unique_unlabelled_relation_per_user'),
        ),
    ]
