services:
  db:
    container_name: storyfinder-postgres-dev-${USER_PREFIX}
    image: postgis/postgis:17-master
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    ports:
      - "127.0.0.1:${HOST_PORT}:5432"
    env_file:
      - docker.env
    volumes:
      - sf-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 5

volumes:
  sf-db-data:
    name: ${USER_PREFIX}-data-dev
    external: true