"""
Django settings for storyfinder project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

try:
    import env as _local
except ModuleNotFoundError:
    _local = None

def _env(key, default=None):
    if key in os.environ:
        return os.environ[key]
    if _local is not None and hasattr(_local, key):
        return getattr(_local, key)
    return default

def _bool(key, default=False):
    raw = _env(key)
    if raw is None:
        return default
    if isinstance(raw, bool):
        return raw
    return str(raw).strip().lower() in ('1', 'true')

def _list(key, default=()):
    raw = _env(key)
    if not raw:
        return list(default)
    if isinstance(raw, (list, tuple)):
        return list(raw)
    return [part.strip() for part in str(raw).split(',') if part.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / 'django_data'
LOG_DIR = DATA_DIR / 'logs/django'

SYSTEM_DATA_DIR = BASE_DIR / 'data'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
RUNNING_IN_DOCKER = _bool('RUNNING_IN_DOCKER', False)
DEBUG = _bool('DEBUG', False)

SECRET_KEY = _env('DJANGO_SECRET_KEY') or 'django-insecure-local-only'
if not DEBUG and SECRET_KEY.startswith('django-insecure'):
    raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DEBUG is off')
    

EXTENSION_ID = _env('CHROME_EXTENSION_ID', 'lhlclfoenmbnghjpiajilbebohmadabo')
EXTENSION_ORIGIN = f'chrome-extension://{EXTENSION_ID}'
SERVER_DOMAIN = _env('SERVER_DOMAIN', 'localhost')

CORS_ALLOW_CREDENTIALS = True
if RUNNING_IN_DOCKER:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', SERVER_DOMAIN, 'testserver']
    CORS_ALLOWED_ORIGINS = [EXTENSION_ORIGIN]
    CSRF_TRUSTED_ORIGINS = [EXTENSION_ORIGIN, f'https://{SERVER_DOMAIN}']
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']
    CORS_ALLOWED_ORIGINS = [EXTENSION_ORIGIN]
    CSRF_TRUSTED_ORIGINS = [EXTENSION_ORIGIN, 'http://localhost:8000']

# SECURITY WARNING: don't run with debug turned on in production!

OPENAI_API_KEY = _env('OPENAI_API_KEY')
OPENAI_MODEL = _env('OPENAI_MODEL')
OPENAI_BASE_URL =_env('OPENAI_BASE_URL')
VIRTUAL_KEY = _env('VIRTUAL_KEY')

ADMIN_USER_PASSWORD = _env('ADMIN_USER_PASSWORD')
ADMIN_USER_TOKEN = _env('ADMIN_USER_TOKEN')
TEST_USER_PASSWORD = _env('TEST_USER_PASSWORD')

POSTGRES_PASSWORD = _env('POSTGRES_PASSWORD')
POSTGRES_PORT = _env('POSTGRES_PORT')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'corsheaders',
    'rest_framework',
    'rest_framework_gis',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'knox',
    'user.apps.UserConfig',
    'graph.apps.GraphConfig',
    'chat.apps.ChatConfig',
    'web.apps.WebConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'storyfinder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'storyfinder.wsgi.application'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': DATA_DIR / 'django_cache',
    }
}


REST_KNOX = {
    'SECURE_HASH_ALGORITHM': 'hashlib.sha512',
    'AUTH_TOKEN_CHARACTER_LENGTH': 64,
    'TOKEN_TTL': timedelta(hours=24),
    'TOKEN_LIMIT_PER_USER': None,
    'AUTO_REFRESH': True,
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

AUTH_USER_MODEL = 'user.CustomUser'

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': _env('POSTGRES_DB', 'postgres'),
        'USER': _env('POSTGRES_USER', 'postgres'),
        'PASSWORD': _env('POSTGRES_PASSWORD'),
        'HOST': 'db' if RUNNING_IN_DOCKER else 'localhost',
        'PORT': _env('POSTGRES_PORT', '5432'),
        'CONN_MAX_AGE': int(_env('DB_CONN_MAX_AGE', 60)),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = DATA_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # Require authentication by default for all endpoints.
    # Individual views can override this with AllowAny where needed (e.g. login).
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'knox.auth.TokenAuthentication',  # must be set. Otherwise, drf would not return 401, but 403
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '200/day',
        'user': '3000/day',
        'login': '30/minute',
    },
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

if RUNNING_IN_DOCKER:
    SECURE_HSTS_SECONDS = 24 * 60 * 60
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SAMESITE = 'None'
else:
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

SILENCED_SYSTEM_CHECKS = ['security.W008']

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.resend.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = _env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = _env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = _env('DEFAULT_FROM_MAIL')


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'chat': {'level': 'INFO'},
        'graph': {'level': 'INFO'},
        'web': {'level': 'INFO'},
        'shared': {'level': 'INFO'},
    },
}
