"""
Django settings for storyfinder project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import env
from typing import Optional, Union
import os

def get_from_env(key: str, default: Optional[Union[str, bool]] = None):
    if key in os.environ:
        return os.environ[key]
    
    if not default:
        return None

    return default

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / 'django_data'
LOG_DIR = DATA_DIR / 'logs/django'

SYSTEM_DATA_DIR = BASE_DIR / 'data'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$b+o#d&_e!@i__2+z7y*7-01e=^a1f_!rxv3yw1$#)ln^6-=da'
CORS_ALLOW_CREDENTIALS = True
ALLOWED_HOSTS = ['localhost']
CORS_ALLOWED_ORIGINS = ['chrome-extension://lhlclfoenmbnghjpiajilbebohmadabo']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_from_env('DEBUG', env.DEBUG)
OPENAI_API_KEY = get_from_env('OPENAI_API_KEY', env.OPENAI_API_KEY)
OPENAI_MODEL = get_from_env('OPENAI_MODEL', env.OPENAI_MODEL)
OPENAI_BASE_URL = get_from_env('OPENAI_BASE_URL', env.OPENAI_API_BASE_URL)
ADMIN_USER_PASSWORD = get_from_env('ADMIN_USER_PASSWORD', env.ADMIN_USER_PASSWORD)
ADMIN_USER_TOKEN = get_from_env('ADMIN_USER_TOKEN', env.ADMIN_USER_TOKEN)
TEST_USER_PASSWORD = get_from_env('TEST_USER_PASSWORD', env.TEST_USER_PASSWORD)

POSTGRES_PASSWORD = get_from_env('POSTGRES_PASSWORD', env.POSTGRES_PASSWORD)
POSTGRES_PORT = get_from_env('POSTGRES_PORT', env.POSTGRES_PORT)


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'corsheaders',
    'rest_framework',
    'rest_framework_gis',
    'drf_spectacular',
    'knox',
    'user.apps.UserConfig',
    'graph.apps.GraphConfig',
    'chat.apps.ChatConfig',
    'web.apps.WebConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'storyfinder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'storyfinder.wsgi.application'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': DATA_DIR / 'django_cache',
    }
}


REST_KNOX = {
    'SECURE_HASH_ALGORITHM': 'hashlib.sha512',
    'AUTH_TOKEN_CHARACTER_LENGTH': 64,
    'TOKEN_TTL': timedelta(hours=24),
    'TOKEN_LIMIT_PER_USER': None,
    'AUTO_REFRESH': True,
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

AUTH_USER_MODEL = 'user.CustomUser'

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': POSTGRES_PASSWORD,
        'HOST': 'localhost',
        'PORT': POSTGRES_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # Require authentication by default for all endpoints.
    # Individual views can override this with AllowAny where needed (e.g. login).
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'knox.auth.TokenAuthentication',  # must be set. Otherwise, drf would not return 401, but 403
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '200/day',
        'user': '3000/day',
        'login': '30/minute',
    },
}


CSRF_TRUSTED_ORIGINS = ['chrome-extension://lhlclfoenmbnghjpiajilbebohmadabo']

SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_HSTS_PRELOAD = False
SILENCED_SYSTEM_CHECKS = [
    'security.W008',  # because we use a reverse-proxy
]
