# Generated by Django 6.0.6 on 2026-09-09 14:30

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField()),
                ('firstname', models.CharField()),
                ('lastname', models.CharField()),
                ('password', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('unlockcode', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
