# Generated by Django 6.0.6 on 2026-09-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_registeruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='unlockcode',
            field=models.CharField(),
        ),
    ]
